# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dfe18b9ade6fbbacda9752bfc20dd462439a233c720ac868c20b3bc436528e50a7ba05fa7729a5a54068345d3323cd6f6591877dbe76c93b813b55baf9b95b58

test:
  secret_key_base: 3634dbab074acd4297752e3ea4ee0e4f446c967cab4f0e4784b36801f37aaf61bcca9cd04b4d13d3322d972c096ecf672c08f8f7691ac86b3e4ab1474a7ec83f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
